In [1]:
import numpy as np

# Question 3

In [5]:
v1 = np.array([0.0283, 0.72, -0.6933])
v2 = np.array([0.7988, -0.4332, -0.4172])

In [8]:
orthogonal = np.isclose(0, np.dot(v1, v2), atol=0.0001)
orthogonal

True

In [9]:
orthonormal = np.isclose(0, np.dot(v1, v2), atol=0.0001) and np.isclose(np.linalg.norm(v1), 1, atol=0.0001) and np.isclose(np.linalg.norm(v2), 1, atol=0.0001)
orthonormal

True

# Question 4

In [15]:
v1 = np.array([0.0283, 0.72, -0.6933])
v2 = np.array([0.7988, -0.4332, -0.4172])
v3 = np.array([0.6008, 0.5421, 0.5875])
y = np.ones(3)
X = np.column_stack((v1, v2, v3))
X

array([[ 0.0283,  0.7988,  0.6008],
       [ 0.72  , -0.4332,  0.5421],
       [-0.6933, -0.4172,  0.5875]])

In [18]:
theta = np.linalg.inv(X.T @ X) @ (X.T @ y)
theta

array([ 0.0550031 , -0.05156644,  1.73041725])

In [20]:
y_hat = theta[0] * v1 + theta[1] * v2 + theta[2] * v3
y_hat

array([1., 1., 1.])